fix: use uniq for assignment in zk config_files recipe
Chef fails if array elts are unique since uniq! returns nil in that case;
this addresses the following error when running chef-client on a zk-server node:

================================================================================
Recipe Compile Error in /var/cache/chef/cookbooks/zookeeper/recipes/config_files.rb
================================================================================

NoMethodError
-------------
undefined method `length' for nil:NilClass

Cookbook Trace:
---------------
  /var/cache/chef/cookbooks/zookeeper/recipes/config_files.rb:34:in `from_file'

 34>>   leader_is_also_server = (zookeeper_hosts.length >= 4)

Squashed commit of the following:

commit 14ae14ef9a27568c0ffd746e0b4c8e5fa41d64c2
Author: Eric Katerman <eric@infochimps.com>
Date:   Mon Mar 24 22:05:38 2014 -0700

    replacing uniq! with uniq since we're assigning, and the former returns nil if already unique

    Change-Id: I46a6b503696f92f05fd1fe881b18df859eb6e9a6

Change-Id: I100925ded600f8d2f7e8032bce07198ed4dec0b8